platform :ios, '7.0'
pod "AFNetworking"
pod 'MBProgressHUD'
pod 'Reachability'
pod 'JSONKit'
pod 'MWPhotoBrowser'
pod 'SSZipArchive'
pod 'FTUtils'
pod 'SPUserResizableView+Pion'
pod 'RDVTabBarController'
pod 'HPGrowingTextView'
pod 'JDStatusBarNotification'
pod 'UMengSocial'
pod 'UMengAnalytics'
pod 'AKSegmentedControl'
pod 'UIImage-Resize'
pod 'ZXingObjC'
pod 'CTAssetsPickerController'

